@startuml
(*) --> "Нажатие кнопки 'Добавить проект'"
--> "Ввод данных"
if "Пользователь ввел данные?" then
  --> [Данные введены] "Система проверяет корректность данных"
  if "Данные корректны?" then
    --> [Данные корректны] "Система проверяет уникальность имени"
    if "Уникальное имя?" then
      --> [Имя уникально] "Система добавляет проект"
      --> "Завершение добавления проетка"
    else
      --> [Имя занято] "Система отображает сообщение об ошибке"
    endif
  else
    --> [Данные не корректны] "Система отображает сообщение об ошибке"
  endif
else
  --> [Данные не введены] "Система отображает сообщение об ошибке"
endif
@enduml