@startuml
(*) --> "Нажатие кнопки 'Удалить'"
--> "Подтвержение удаления проекта"
if "Удаление подтверждено?" then
  --> [Подтверждено] "Система удаляет проект"
  --> "Система прекращает отображение информации о проекте"
  --> "Завершение удаления проетка"
else
  --> [Не подтверждено] "Завершение удаления проетка"
endif
@enduml