@startuml
(*) --> "Нажатие кнопки 'Изменить'"
--> "Изменение данных"
--> "Подтвержение изменения данных"
if "Изменения подтверждены?" then
  --> [Подтверждены] "Система проверяет корректность данных"
  if "Данные корректны?" then
    --> [Данные корректны] "Система проверяет уникальность имени"
    if "Имя уникально?" then
      --> [Имя уникально] "Система изменяет проект"
      --> "Завершение изменения проетка"
    else
      --> [Имя занято] "Система отображает сообщение об ошибке"
    endif
  else
    --> [Данные не корректны] "Система отображает сообщение об ошибке"
  endif
else
  --> [Не подтверждены] "Завершение изменения проетка"
endif
@enduml