@startuml
(*) --> "Нажатие кнопки 'Фильтр'"
--> "Настройка фильтра"
--> "Подтвержение применения фильтра"
if "Применение подтверждено?" then
  --> [Подтверждено] "Система применяет фильтр к списку проектов"
  --> "Завершение настройки фильтра"
else
  --> [Не подтверждено] "Завершение настройки фильтра"
endif
@enduml