@startuml

[*] --> ДобавлениеПроекта : Кликнул на 'Добавить'

state ДобавлениеПроекта {
  [*] --> ВводДанных : Добавить новый проект
  ВводДанных --> ДобавлениеПроекта : Отмена
  ВводДанных --> ПроверкаДанных : Подтверждение
  ПроверкаДанных --> ПроверкаУникальностьИмени : Корректны
  ПроверкаДанных --> ВводДанных : Ошибка
  ПроверкаУникальностьИмени --> ДобавитьПроект : Уникально 
  ПроверкаУникальностьИмени --> ВводДанных : Не уникально 
  ДобавитьПроект --> ДобавлениеПроекта : Проект добавлен
}

@enduml