@startuml
scale 450 width

[*] --> ПроектНеВыбран

state ПроектНеВыбран {
  [*] --> ВыборПроекта
  ВыборПроекта --> ПолучениеДанныхОПроекте : Проект выбран
  ВыборПроекта --> ВыборПроекта : Проект не выбрна
  ПолучениеДанныхОПроекте --> ПроектВыбран : Данные получены

state ПроектВыбран {
  [*] --> ОтображениеДанныхОПроекте
  ОтображениеДанныхОПроекте --> УдалитьПроект : Кликнул 'удалить'
  УдалитьПроект --> ПодтверждениеУдаленияПроекта
  ПодтверждениеУдаленияПроекта --> ОтображениеДанныхОПроекте : Отменено
  ПодтверждениеУдаленияПроекта --> ПроектНеВыбран : Подтверждено
  ОтображениеДанныхОПроекте --> ИзменениеПроекта : Кликнул 'Изменить'
}
}


state ИзменениеПроекта {
  [*] --> ИзменениеДанных
  ИзменениеДанных --> ПроектВыбран : Отмена
  ИзменениеДанных --> ПодтвердитьИзменения : Изменено
  ПодтвердитьИзменения --> ПроектВыбран : Отменить
  ПодтвердитьИзменения --> ДанныеИзменены : Подтвердить
  ДанныеИзменены --> ПроектВыбран
}

@enduml