@startuml

state НеОтфильтрованы {
  [*] --> Ожидание 
  Ожидание --> НастройкаФильтра : Кликнул 'Фильтр'
  ПрименитьФильтр --> Отфильтрованы : Фильтр применен

  state Отфильтрованы {
  [*] -->  НеОтфильтрованы : Кликнул 'Отменить фильтр'
  [*] --> НастройкаФильтра : Кликнул 'Фильтр'
  }
}

state НастройкаФильтра {
  [*] --> ВводДанныхФильтра
  ВводДанныхФильтра --> НеОтфильтрованы : Отмена
  ВводДанныхФильтра --> ПодтверждениеУстановкиФильтра 
  ПодтверждениеУстановкиФильтра --> НеОтфильтрованы : Отмена
  ПодтверждениеУстановкиФильтра --> ПрименитьФильтр : Подтвердено
}

@enduml